(() => {
const S=window.SCENARIO;
const $=s=>document.querySelector(s);
const state={index:0,choices:[]};
const startScreen=$('#startScreen'),game=$('#gameScreen'),end=$('#endScreen'),choicePanel=$('#choicePanel'),resultPanel=$('#resultPanel');
$('#appTitle').textContent=S.meta.title; $('#subtitle').textContent=S.meta.subtitle; $('#status').textContent=S.meta.status; $('#building').textContent=S.meta.building;
$('#principles').innerHTML=S.meta.principles.map(x=>`<div class="principle">${esc(x)}</div>`).join('');

function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function paras(t){return String(t||'').split(/\n\s*\n/).filter(Boolean).map(x=>`<p>${linkTerms(x)}</p>`).join('')}
const terms=Object.keys(S.glossary||{}).sort((a,b)=>b.length-a.length);
function linkTerms(text){let s=esc(text); for(const term of terms){const re=new RegExp(`\\b${term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'gi');s=s.replace(re,m=>`<span class="term" data-term="${esc(term)}">${m}</span>`);}return s;}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden');bindTerms($('#modalContent'));bindSystems($('#modalContent'));}
function showTerm(term){const g=S.glossary?.[term];if(!g)return;openModal(`<div class="small">BEGRIP</div><h2>${esc(term)}</h2><p>${esc(g.definition)}</p><div class="operational"><strong>Operationeel in deze casus</strong><br>${esc(g.operational)}</div>`)}
function showGlossary(){let h='<h2>Begrippen</h2>';for(const [k,v] of Object.entries(S.glossary||{}))h+=`<div class="glossItem"><h3>${esc(k)}</h3><p>${esc(v.definition)}</p><div class="operational"><strong>Operationeel:</strong> ${esc(v.operational)}</div></div>`;openModal(h)}
function showSources(){openModal(`<h2>Bronnen en status</h2><p>Deze webcasus is een didactische oefentoepassing en geen vastgesteld inzetprotocol.</p><ul><li>VGGM – Brandbestrijding hoogbouw (lesmateriaal)</li><li>Concept Handboek Brandbestrijding Hoogbouw VGGM 2026</li><li>Scenario / Stroomschema Hoogbouw VGGM 2026</li><li>Handboek Incidentbestrijding Hoogbouw, Brandweer Rotterdam-Rijnmond (2024)</li><li>BPBB Train-de-trainer 2026 – LD en watertransport op hoogte</li></ul><div class="sourceNote">${esc(S.meta.sourceNote)}</div>`)}
function showScenarios(){const g=S.meta.scenarioGuide;if(!g)return;let h=`<div class="small">DENKKADER</div><h2>${esc(g.title)}</h2><p>${esc(g.intro)}</p>`;for(const i of g.items)h+=`<section class="guideItem"><h3>${esc(i.title)}</h3><p>${esc(i.text)}</p></section>`;h+=`<div class="roleBox"><strong>Belangrijk:</strong> het scenario is geen vast label. Nieuwe informatie kan betekenen dat het incident opnieuw moet worden geclassificeerd en dat prioriteiten, opdrachten en capaciteit moeten veranderen.</div>`;openModal(h)}
function bindTerms(root=document){root.querySelectorAll('.term').forEach(el=>el.addEventListener('click',()=>showTerm(el.dataset.term)))}
function systemPanel(n){if(!n.systems?.length)return '';return `<section class="systemsPanel"><div class="systemsHead"><strong>VGGM / BPBB-systemen die hier meespelen</strong><span class="systemsHint">klik voor uitleg</span></div><div class="systemChips">${n.systems.map(k=>`<button class="systemChip" data-system="${esc(k)}">${esc(k)}</button>`).join('')}</div></section>`}
function bindSystems(root=document){root.querySelectorAll('.systemChip').forEach(b=>b.addEventListener('click',()=>{const t=S.systemDefinitions?.[b.dataset.system];openModal(`<div class="small">VGGM / BPBB</div><h2>${esc(b.dataset.system)}</h2><p>${esc(t||'Geen aanvullende uitleg beschikbaar.')}</p>`)}))}
function mediaHtml(n){if(!n.media)return '';return `<figure class="scenarioMedia"><img src="${esc(n.media.src)}" alt="${esc(n.media.caption)}" loading="lazy"><figcaption><span>${esc(n.media.caption)}</span><small>${esc(n.media.source||'')}</small></figcaption></figure>${(n.mediaGallery||[]).map(m=>`<figure class="scenarioMedia"><img src="${esc(m.src)}" alt="${esc(m.caption)}" loading="lazy"><figcaption><span>${esc(m.caption)}</span><small>${esc(m.source||'')}</small></figcaption></figure>`).join('')}`}
function renderNode(){const n=S.nodes[state.index];$('#progressText').textContent=`Keuzemoment ${n.id} van ${S.nodes.length}`;$('#progressBar').style.width=`${((n.id-1)/S.nodes.length)*100}%`;$('#roleBadge').textContent=n.role;$('#roleNote').textContent=n.roleNote;$('#incidentTime').textContent=`INCIDENT • beslismoment ${n.id}`;$('#nodeTitle').textContent=n.title;let extra=(S.meta.scenarioGuide&&[8,16,17].includes(n.id))?'<button class="scenarioGuideInline" id="scenarioInline">Bekijk scenario-uitleg</button>':'';$('#situation').innerHTML=paras(n.situation)+extra+mediaHtml(n)+systemPanel(n);bindTerms($('#situation'));bindSystems($('#situation'));if($('#scenarioInline'))$('#scenarioInline').addEventListener('click',showScenarios);choicePanel.innerHTML='';resultPanel.classList.add('hidden');n.choices.forEach(c=>{const b=document.createElement('button');b.className='choiceBtn';b.innerHTML=`<span class="choiceKey">${c.id}</span><span>${linkTerms(c.text)}</span>`;b.addEventListener('click',()=>choose(n,c));choicePanel.appendChild(b);bindTerms(b)});choicePanel.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function deepDive(n,c){const alt=n.choices.filter(x=>x.id!==c.id).map(x=>`<div class="compareItem"><strong>Keuze ${x.id}</strong><p>${linkTerms(x.text)}</p><div class="small">${linkTerms(x.rationale)}</div></div>`).join('');return `<div class="deepDive"><div class="small">VERDIEPENDE NABESPREKING • KEUZEMOMENT ${n.id}</div><h2>${esc(n.title)}</h2>${n.deepDive?`<div class="deepText">${paras(n.deepDive)}</div>`:''}<h3>Jouw keuze ${c.id}</h3><p><strong>${linkTerms(c.text)}</strong></p><p>${linkTerms(c.deepDive||c.rationale)}</p>${n.discussionQuestion?`<div class="discussionQuestion"><strong>Bespreekvraag</strong><p>${linkTerms(n.discussionQuestion)}</p></div>`:''}<h3>Andere opties</h3><div class="compareGrid">${alt}</div><div class="sourceNote">${esc(S.meta.sourceNote)}</div></div>`}
function choose(n,c){state.choices.push({node:n.id,choice:c.id});choicePanel.classList.add('hidden');resultPanel.classList.remove('hidden');resultPanel.innerHTML=`<div class="resultCard"><div class="small">GEVOLG VAN JE KEUZE</div><h3>${esc(n.title)}</h3><div class="consequence">${linkTerms(c.consequence)}</div><div class="feedbackActions"><button class="feedbackToggle" id="whyBtn">Korte duiding</button><button class="deepDiveBtn" id="deepBtn">Verdiepende uitleg</button></div><div id="feedback" class="feedback hidden"><p>${linkTerms(c.rationale)}</p></div><div class="nextRow"><button class="secondary" id="nextBtn">${state.index===S.nodes.length-1?'Naar einddebrief':'Verder met de inzet'}</button></div></div>`;bindTerms(resultPanel);$('#whyBtn').addEventListener('click',()=>$('#feedback').classList.toggle('hidden'));$('#deepBtn').addEventListener('click',()=>openModal(deepDive(n,c)));$('#nextBtn').addEventListener('click',()=>{if(state.index<S.nodes.length-1){state.index++;renderNode()}else finish()});resultPanel.scrollIntoView({behavior:'smooth',block:'start'})}
function finish(){game.classList.add('hidden');end.classList.remove('hidden');let sections=(S.debriefSections||[]).map(s=>`<section class="debriefTheme"><h3>${esc(s.title)}</h3><p class="debriefQ">${esc(s.question)}</p><ul>${(s.points||[]).map(x=>`<li>${linkTerms(x)}</li>`).join('')}</ul></section>`).join('');let hist=state.choices.map(ch=>{const n=S.nodes.find(x=>x.id===ch.node),c=n.choices.find(x=>x.id===ch.choice);return `<details class="historyItem"><summary>Keuzemoment ${n.id} – ${esc(n.title)} <span>keuze ${c.id}</span></summary><div class="historyBody"><p><strong>Jouw besluit:</strong> ${linkTerms(c.text)}</p><p><strong>Operationeel gevolg:</strong> ${linkTerms(c.consequence)}</p><p><strong>Duiding:</strong> ${linkTerms(c.rationale)}</p>${n.discussionQuestion?`<div class="discussionQuestion"><strong>Bespreekvraag</strong><p>${linkTerms(n.discussionQuestion)}</p></div>`:''}</div></details>`}).join('');let close=(S.closingQuestions||[]).map(q=>`<p class="closingQuestion">${esc(q)}</p>`).join('');end.innerHTML=`<div class="card endCard"><span class="status">EINDDEBRIEF</span><h2>Terugkijken op de totale inzet</h2><p class="lead">Geen score en geen goed/fout-eindoordeel. Gebruik de vragen hieronder om te beoordelen hoe je beeldvorming, tactiek en organisatie zich tijdens de inzet hebben ontwikkeld.</p>${S.meta.scenarioGuide?'<button class="scenarioGuideInline" id="scenarioEnd">Bekijk scenario-uitleg</button>':''}<div class="debriefGrid">${sections}</div><section class="closingBlock"><h3>Als je deze inzet opnieuw zou doen</h3>${close}</section><h3>Jouw beslissingen</h3><div class="history">${hist}</div><div class="nextRow"><button class="primary" id="restartBtn">Casus opnieuw spelen</button></div></div>`;bindTerms(end);if($('#scenarioEnd'))$('#scenarioEnd').addEventListener('click',showScenarios);$('#restartBtn').addEventListener('click',()=>location.reload());window.scrollTo({top:0,behavior:'smooth'})}
$('#glossaryBtn').addEventListener('click',showGlossary);$('#sourcesBtn').addEventListener('click',showSources);if($('#scenarioBtn'))$('#scenarioBtn').addEventListener('click',showScenarios);$('#modalClose').addEventListener('click',()=>$('#modal').classList.add('hidden'));$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')});$('#startBtn').addEventListener('click',()=>{startScreen.classList.add('hidden');game.classList.remove('hidden');renderNode()});
})();
